config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :usrs
  resources :resps
  resources :posts
  resources :tests

  root 'application#index'

  
  

end

app/models/resp.rb
class Resp < ActiveRecord::Base
end

app/controllers/resps_controller.rb
class RespsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create
  before_action :set_resp, only: [:show, :edit, :update, :destroy]

  # GET /resps
  # GET /resps.json
  def index
    @resps = Resp.all
  end

  # GET /resps/1
  # GET /resps/1.json
  def show
    respond_to do |format|
        format.html 
        format.json { render :text => "Fuck!"}
    end
  end

  # GET /resps/new
  def new
    @resp = Resp.new
  end

  # GET /resps/1/edit
  def edit
  end

  # POST /resps
  # POST /resps.json
  def create
    @resp = Resp.new(resp_params)

    respond_to do |format|
      if @resp.save
        format.html { redirect_to @resp, notice: 'Resp was successfully created.' }
        format.json { render :show, status: :created, location: @resp }
      else
        format.html { render :new }
        format.json { render json: @resp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resps/1
  # PATCH/PUT /resps/1.json
  def update
    respond_to do |format|
      if @resp.update(resp_params)
        format.html { redirect_to @resp, notice: 'Resp was successfully updated.' }
        format.json { render :show, status: :ok, location: @resp }
      else
        format.html { render :edit }
        format.json { render json: @resp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resps/1
  # DELETE /resps/1.json
  def destroy
    @resp.destroy
    respond_to do |format|
      format.html { redirect_to resps_url, notice: 'Resp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resp
      @resp = Resp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resp_params
      params.permit(:name, :heart_beat, :latitude, :longitude)
    end
end

app/helpers/resps_helper.rb
module RespsHelper
end

app/views/resps/_form.html.erb
<%= form_for(@resp) do |f| %>
  <% if @resp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resp.errors.count, "error") %> prohibited this resp from being saved:</h2>

      <ul>
      <% @resp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :heart_beat %><br>
    <%= f.number_field :heart_beat %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resps/edit.html.erb
<h1>Editing Resp</h1>

<%= render 'form' %>

<%= link_to 'Show', @resp %> |
<%= link_to 'Back', resps_path %>

app/views/resps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Heart beat</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resps.each do |resp| %>
      <tr>
        <td><%= resp.name %></td>
        <td><%= resp.heart_beat %></td>
        <td><%= resp.latitude %></td>
        <td><%= resp.longitude %></td>
        <td><%= link_to 'Show', resp %></td>
        <td><%= link_to 'Edit', edit_resp_path(resp) %></td>
        <td><%= link_to 'Destroy', resp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resp', new_resp_path %>

app/views/resps/new.html.erb
<h1>New Resp</h1>

<%= render 'form' %>

<%= link_to 'Back', resps_path %>

app/views/resps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resp.name %>
</p>

<p>
  <strong>Heart beat:</strong>
  <%= @resp.heart_beat %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @resp.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @resp.longitude %>
</p>

<%= link_to 'Edit', edit_resp_path(@resp) %> |
<%= link_to 'Back', resps_path %>